[project]
name = "poocam-pi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "adafruit-blinka>=8.67.0 ; sys_platform == 'linux'",
    "adafruit-circuitpython-amg88xx>=1.2.26 ; sys_platform == 'linux'",
    "board>=1.0",
    "poocam-core",
    "rpi-gpio>=0.7.1 ; sys_platform == 'linux'",
]

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
poocam-core = { workspace = true }
